In [108]:
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd
# define a matrix
A = array([
	[1,2,3,4,5,6,7,8,9,10],
	[11,12,13,14,15,16,17,18,19,20],
	[21,22,23,24,25,26,27,28,29,30]])
print(A)
# Singular-value decomposition
U, s, VT = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = diag(s)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [109]:
A.shape, U.shape, Sigma.shape, VT.shape

((3, 10), (3, 3), (3, 10), (10, 10))

In [115]:
U, Sigma, VT

(array([[-0.19101157, -0.89266338,  0.40824829],
        [-0.51371859, -0.26348917, -0.81649658],
        [-0.8364256 ,  0.36568503,  0.40824829]]),
 array([[9.69657342e+01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 7.25578339e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 1.48879510e-15, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00]]),
 array([[-0.24139304, -0.25728686, -0.27318068, -0.2890745 , -0.30496832,
         -0.32086214, -0.33675595, -0.35264977, -0.36854359, -0.38443741],
        [ 0.53589546,  0.42695236,  0.31800926,  0.20906617,  0.10012307,
         -0.00882003, -0.11776313, -0.22670623, -0.33564933, -

In [110]:
print(pd.DataFrame(Sigma))

           0         1             2    3    4    5    6    7    8    9
0  96.965734  0.000000  0.000000e+00  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1   0.000000  7.255783  0.000000e+00  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2   0.000000  0.000000  1.488795e-15  0.0  0.0  0.0  0.0  0.0  0.0  0.0


In [111]:
#select
n_elements = 2
NSigma = Sigma[:, :n_elements]
NVT = VT[:n_elements, :]
print(pd.DataFrame(NSigma))

           0         1
0  96.965734  0.000000
1   0.000000  7.255783
2   0.000000  0.000000


In [112]:
A.shape, U.shape, NSigma.shape, NVT.shape

((3, 10), (3, 3), (3, 2), (2, 10))

In [116]:
U, NSigma, NVT

(array([[-0.19101157, -0.89266338,  0.40824829],
        [-0.51371859, -0.26348917, -0.81649658],
        [-0.8364256 ,  0.36568503,  0.40824829]]),
 array([[96.96573419,  0.        ],
        [ 0.        ,  7.25578339],
        [ 0.        ,  0.        ]]),
 array([[-0.24139304, -0.25728686, -0.27318068, -0.2890745 , -0.30496832,
         -0.32086214, -0.33675595, -0.35264977, -0.36854359, -0.38443741],
        [ 0.53589546,  0.42695236,  0.31800926,  0.20906617,  0.10012307,
         -0.00882003, -0.11776313, -0.22670623, -0.33564933, -0.44459242]]))

In [113]:
# reconstruct
B = U.dot(NSigma.dot(NVT))
print(B)
# transform
T = U.dot(NSigma)
print(T)
T = A.dot(NVT.T)
print(T)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]
[[-18.52157747  -6.47697214]
 [-49.81310011  -1.91182038]
 [-81.10462276   2.65333138]]
[[-18.52157747  -6.47697214]
 [-49.81310011  -1.91182038]
 [-81.10462276   2.65333138]]


In [ ]:
from sklearn.decomposition import TruncatedSVD

In [96]:
ets = TruncatedSVD(n_components = 2).fit_transform(A)

In [97]:
ets

array([[18.52157747,  6.47697214],
       [49.81310011,  1.91182038],
       [81.10462276, -2.65333138]])